-- 创建TG账号表
CREATE TABLE IF NOT EXISTS `tg_accounts` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '归属用户ID',
    `phone` VARCHAR(20) NOT NULL UNIQUE COMMENT '手机号',
    `session_data` TEXT COMMENT 'Telegram会话数据',
    `proxy_id` BIGINT UNSIGNED NULL COMMENT '绑定的代理ID',
    `status` ENUM('new', 'normal', 'warning', 'restricted', 'dead', 'cooling', 'maintenance') NOT NULL DEFAULT 'new' COMMENT '账号状态',
    `health_score` DECIMAL(3,2) NOT NULL DEFAULT 1.00 COMMENT '健康度分数(0.00-1.00)',
    `last_check_at` TIMESTAMP NULL COMMENT '最后检查时间',
    `last_used_at` TIMESTAMP NULL COMMENT '最后使用时间',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_tg_accounts_phone` (`phone`),
    INDEX `idx_tg_accounts_user_id` (`user_id`),
    INDEX `idx_tg_accounts_proxy_id` (`proxy_id`),
    INDEX `idx_tg_accounts_status` (`status`),
    INDEX `idx_tg_accounts_health_score` (`health_score`),
    INDEX `idx_tg_accounts_last_check_at` (`last_check_at`),
    INDEX `idx_tg_accounts_last_used_at` (`last_used_at`),
    INDEX `idx_tg_accounts_created_at` (`created_at`),
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`proxy_id`) REFERENCES `proxy_ips` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TG账号表';
