-- 创建任务表
CREATE TABLE IF NOT EXISTS `tasks` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '创建用户ID',
    `account_id` BIGINT UNSIGNED NOT NULL COMMENT '执行账号ID',
    `task_type` ENUM('check', 'private_message', 'broadcast', 'verify_code', 'group_chat') NOT NULL COMMENT '任务类型',
    `status` ENUM('pending', 'queued', 'running', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'pending' COMMENT '任务状态',
    `priority` INT NOT NULL DEFAULT 5 COMMENT '优先级(1-10)',
    `config` JSON COMMENT '任务配置(JSON格式)',
    `result` JSON COMMENT '执行结果(JSON格式)',
    `scheduled_at` TIMESTAMP NULL COMMENT '计划执行时间',
    `started_at` TIMESTAMP NULL COMMENT '开始执行时间',
    `completed_at` TIMESTAMP NULL COMMENT '完成时间',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_tasks_user_id` (`user_id`),
    INDEX `idx_tasks_account_id` (`account_id`),
    INDEX `idx_tasks_task_type` (`task_type`),
    INDEX `idx_tasks_status` (`status`),
    INDEX `idx_tasks_priority` (`priority`),
    INDEX `idx_tasks_scheduled_at` (`scheduled_at`),
    INDEX `idx_tasks_started_at` (`started_at`),
    INDEX `idx_tasks_completed_at` (`completed_at`),
    INDEX `idx_tasks_created_at` (`created_at`),
    INDEX `idx_tasks_user_status` (`user_id`, `status`),
    INDEX `idx_tasks_account_status` (`account_id`, `status`),
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`account_id`) REFERENCES `tg_accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务表';
